from __future__ import annotations

from twitchio import eventsub

AFFILIATE_ONLY_SUBS = frozenset(
    {
        "ChannelPointsRedemptionAdd",
        "ChannelBitsUse",
        "Subscribe",
        "SubscriptionGift",
        "SubscriptionMessage",
        "ChannelPollBegin",
        "ChannelPollProgress",
        "ChannelPollEnd",
        "ChannelPredictionBegin",
        "ChannelPredictionProgress",
        "ChannelPredictionLock",
        "ChannelPredictionEnd",
        "HypeTrainBegin",
        "HypeTrainProgress",
        "HypeTrainEnd",
    }
)


def build_subscription_list(
    *,
    broadcaster_id: str,
    bot_id: str,
) -> list[tuple[str, eventsub.SubscriptionPayload, bool, str | None, str]]:
    bid = broadcaster_id
    uid = bot_id
    return [
        (
            "ChatMessage",
            eventsub.ChatMessageSubscription(broadcaster_user_id=bid, user_id=uid),
            True,
            "user:read:chat",
            "bot",
        ),
        (
            "StreamOnline",
            eventsub.StreamOnlineSubscription(broadcaster_user_id=bid),
            False,
            None,
            "bot",
        ),
        (
            "StreamOffline",
            eventsub.StreamOfflineSubscription(broadcaster_user_id=bid),
            False,
            None,
            "bot",
        ),
        (
            "Follow",
            eventsub.ChannelFollowSubscription(broadcaster_user_id=bid, moderator_user_id=uid),
            False,
            "moderator:read:followers",
            "bot",
        ),
        (
            "Raid",
            eventsub.ChannelRaidSubscription(to_broadcaster_user_id=bid),
            False,
            None,
            "bot",
        ),
        (
            "Subscribe",
            eventsub.ChannelSubscribeSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:subscriptions",
            "channel",
        ),
        (
            "SubscriptionGift",
            eventsub.ChannelSubscriptionGiftSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:subscriptions",
            "channel",
        ),
        (
            "SubscriptionMessage",
            eventsub.ChannelSubscribeMessageSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:subscriptions",
            "channel",
        ),
        (
            "ChannelPointsRedemptionAdd",
            eventsub.ChannelPointsRedeemAddSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:redemptions",
            "channel",
        ),
        (
            "ChannelBitsUse",
            eventsub.ChannelBitsUseSubscription(broadcaster_user_id=bid),
            False,
            "bits:read",
            "channel",
        ),
        (
            "ChatMessageDelete",
            eventsub.ChatMessageDeleteSubscription(broadcaster_user_id=bid, user_id=uid),
            False,
            "user:read:chat",
            "bot",
        ),
        (
            "ChannelBan",
            eventsub.ChannelBanSubscription(broadcaster_user_id=bid),
            False,
            "channel:moderate",
            "channel",
        ),
        (
            "ChannelUnban",
            eventsub.ChannelUnbanSubscription(broadcaster_user_id=bid),
            False,
            "channel:moderate",
            "channel",
        ),
        (
            "AutomodMessageHold",
            eventsub.AutomodMessageHoldSubscription(
                broadcaster_user_id=bid,
                moderator_user_id=uid,
            ),
            False,
            "moderator:manage:automod",
            "bot",
        ),
        (
            "AutomodMessageUpdate",
            eventsub.AutomodMessageUpdateSubscription(
                broadcaster_user_id=bid,
                moderator_user_id=uid,
            ),
            False,
            "moderator:manage:automod",
            "bot",
        ),
        (
            "ChannelPollBegin",
            eventsub.ChannelPollBeginSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:polls",
            "channel",
        ),
        (
            "ChannelPollProgress",
            eventsub.ChannelPollProgressSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:polls",
            "channel",
        ),
        (
            "ChannelPollEnd",
            eventsub.ChannelPollEndSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:polls",
            "channel",
        ),
        (
            "ChannelPredictionBegin",
            eventsub.ChannelPredictionBeginSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:predictions",
            "channel",
        ),
        (
            "ChannelPredictionProgress",
            eventsub.ChannelPredictionProgressSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:predictions",
            "channel",
        ),
        (
            "ChannelPredictionLock",
            eventsub.ChannelPredictionLockSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:predictions",
            "channel",
        ),
        (
            "ChannelPredictionEnd",
            eventsub.ChannelPredictionEndSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:predictions",
            "channel",
        ),
        (
            "HypeTrainBegin",
            eventsub.HypeTrainBeginSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:hype_train",
            "channel",
        ),
        (
            "HypeTrainProgress",
            eventsub.HypeTrainProgressSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:hype_train",
            "channel",
        ),
        (
            "HypeTrainEnd",
            eventsub.HypeTrainEndSubscription(broadcaster_user_id=bid),
            False,
            "channel:read:hype_train",
            "channel",
        ),
    ]
